Feature/loading screen
yukimiyake0607/yumemi_clima_training pull request #16
Opened 2024-08-29 07:41 UTC by yukimiyake0607

## 課題

close #4 

## 対応箇所

・アプリ起動時の画面をLoadingScreenに変更
・LoadingScreenの初期ライフサイクルメソッドがすべて終了してから0.5秒後にsession2までで作成していた画面(HomeScreen)に遷移するように変更

## 動作

https://github.com/user-attachments/assets/1f429117-9ed0-44e3-89b5-c4b6a55e1404

2024-08-29 08:16 UTC, morikann requested changes
https://github.com/yukimiyake0607/yumemi_clima_training/issues/4
の動作イメージを見てもらうと、Close ボタン押下時に緑の画面に戻ってその 0.5 秒後に再度天気のページに遷移する処理も必要です。

2024-08-29 09:17 UTC, yukimiyake0607 commented
Close ボタン押下時に緑の画面に戻ってその 0.5 秒後に再度天気のページに遷移する処理を追加しました。
確認よろしくお願いします。

2024-09-14 08:48 UTC, morikann commented on lib/ui/screens/loading_screen.dart
> +    );
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
`Scaffold` に `backgroundColor` を指定するだけで良さそうです。（`Container` は const を付けられないのでパフォーマンス的に良くありません。出来る限り使わない方が良いです。）

```suggestion
   return const Scaffold(
      backgroundColor: Colors.green,
    );
```

2024-09-14 08:48 UTC, morikann commented on lib/ui/screens/home_screen.dart
> +  final VoidCallback _onReturn;
![next-badge](https://img.shields.io/badge/review-next-blueviolet) 
ButtonRow のインタフェースとして onReturn という命名は ButtonRow を使う側からしたらよく分からないので、インタフェースの命名を考慮できると良さそうです。

2024-09-14 08:48 UTC, morikann commented on lib/ui/screens/home_screen.dart
> +  final VoidCallback _onReturn;
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
close ボタン押下後に再度ホーム画面に戻る処理は、意外と実装が難しいのですが自力で実装できていてすごいです！

2024-09-14 08:48 UTC, morikann commented on lib/ui/screens/home_screen.dart
> +  final VoidCallback _onReturn;
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
ただ、0.5 秒後にホームスクリーンに遷移する処理は LoadingScreen の責務であり、HomeScreen の責務ではないので、LoadingScreen 内で処理を完結できるようにすると良さそうです。

2024-09-14 08:48 UTC, morikann commented on lib/ui/screens/loading_screen.dart
> +  }
![FYI](https://img.shields.io/badge/review-FYI-pink) 
以下のように実装することで、LoadingScreen 内のみで 0.5 秒後遷移の処理が実装できます。

```suggestion
  void initState() {
    super.initState();
    unawaited(
      WidgetsBinding.instance.endOfFrame.then(
        (_) => _navigateToHomeScreen(),
      ),
    );
  }

  Future<void> _navigateToHomeScreen() async {
    await Future<void>.delayed(const Duration(milliseconds: 500));
    if (!mounted) {
      return;
    }

    await Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => const HomeScreen(),
      ),
    );

    await _navigateToHomeScreen();
  }
```

2024-09-17 08:36 UTC, yukimiyake0607 commented on lib/ui/screens/home_screen.dart
> +  final VoidCallback _onReturn;
遷移する処理をLoadingScreen内で完結するように修正しました。
以下で確認お願いします。
aa727c0a55d4a3d543ec26ec6ef9fb5ca85c575f

2024-09-17 08:39 UTC, yukimiyake0607 commented on lib/ui/screens/loading_screen.dart
> +    );
constが付与できるように以下で修正しました。
確認お願いします。
be22fc7be0ffcec09ab5f5dbe7c27396c7862f5e

2024-09-17 08:41 UTC, yukimiyake0607 commented on lib/ui/screens/home_screen.dart
> +  final VoidCallback _onReturn;
HomeScreenに遷移するメソッドの責務をLoadingScreenにするように変更したため、onReturn変数を削除しました。
もし変更するのであれば、onCloseButtonPressedですか？

2024-09-22 03:17 UTC, morikann commented on lib/ui/screens/home_screen.dart
> +  final VoidCallback _onReturn;
`onCloseButtonPressed` で良さそうです！
ただ、ページに対して onコールバックを渡すことはあまりない気がするので、もしあればの話と捉えていただければ🙏

2024-09-22 03:23 UTC, morikann approved these changes
LGTM です！
ご対応ありがとうございます！

2024-09-22 12:01 UTC, merged