Feature/add mixin
yukimiyake0607/yumemi_clima_training pull request #17
Opened 2024-09-02 13:32 UTC by yukimiyake0607

## 課題

close #5 

## 対応箇所

LoadScreen(StatefuklWidget)内のinitStateで使用していたメソッドをMixinで実装
※メソッド：緑画面(LoadingScreen)から0.5秒後にHomeScreenへ遷移する

`mixin NavigateToHomescreenMixin<T extends StatefulWidget> on State<T> {
  void navigateToHomeScreen() {
    unawaited(
      WidgetsBinding.instance.endOfFrame.then(
        (_) {
          if (!mounted) {
            return;
          }
          Future.delayed(const Duration(milliseconds: 500), () {
            if (!mounted) {
              return;
            }

            unawaited(
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (_) => HomeScreen(onReturn: navigateToHomeScreen),
                ),
              ),
            );
          });
        },
      ),
    );
  }
}`

## 動作

動作の変更はありません

2024-09-14 08:56 UTC, morikann requested changes

2024-09-14 08:56 UTC, morikann commented on lib/models/navigate_to_homescreen_mixin.dart
> +}
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
現在の実装だと「HomeScreen に Navigate する」という Mixin になっています。
課題の仕様は「レイアウトが表示された後に「何かしらの処理」を行う Mixin を作成する」となっているため、命名としては AfterLayoutMixin などが適していると思います。（実装は [flutter_after_layout](https://github.com/fluttercommunity/flutter_after_layout/blob/master/lib/after_layout.dart) パッケージが今回の課題で作成する Mixin と類似しているため参考にしていただければと思います）

また、仕様で「作成した Mixin の使用先で「何かしらの処理」を記述できるようにする」とあるため、navigatoToHomeScreen() メソッドは Mixin 使用先（LoadingScreen）で実装していただければと思います。

2024-09-14 09:07 UTC, morikann commented on lib/models/navigate_to_homescreen_mixin.dart
> +  Future<void> navigateToHomeScreen() async {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg) 
この mixin はモデルではないと思うので、mixin ディレクトリ or utils ディレクトリなどを作成して、その配下に移動すると良さそうです。

2024-09-17 13:29 UTC, yukimiyake0607 commented on lib/models/navigate_to_homescreen_mixin.dart
> +}
Mixinの命名を変更しました
f9cf4fdc2867652bc0cfc0e7ddbe43682f948849

2024-09-17 13:32 UTC, yukimiyake0607 commented on lib/models/navigate_to_homescreen_mixin.dart
> +}
仕様に合わせて、Mixin内でinitStateを実装することに変更しました。
また、それに応じてLoadingScreenに実装も変更しました。
確認お願いします。
b53ffed107b3c11a4e093e27a1cafbc7c3225a25
5b1259f6615fadbfbf94cacff0afdeb3a1aa8ef3
b5604bb723bee49f8dcc850ab8e3a9b45a100df7

2024-09-17 13:33 UTC, yukimiyake0607 commented on lib/models/navigate_to_homescreen_mixin.dart
> +  Future<void> navigateToHomeScreen() async {
Mixinのディレクトリを新規作成しました。
4c86fbb5931df8e6d6d6ae6d196b86ac1f9f04f6

2024-09-22 03:28 UTC, morikann commented on lib/models/navigate_to_homescreen_mixin.dart
> +}
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
ほぼ完璧に実装していて凄いです。
`navigateToHomeScreen` もインタフェースの定義のみにすることで、実装を強制させることができていて流石です！

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
`navigateToHomeScreen` の戻り値を `FutureOr<void>` にしている理由はありますでしょうか？

2024-09-22 03:30 UTC, morikann reviewed
1点質問させていただいたのでご確認お願いします！それ以外は完璧でした！

2024-09-22 03:32 UTC, morikann approved these changes
実装としては問題なかったので Approve させていただきます！
質問だけ確認いただいた後、マージしていただければと思います！

2024-09-22 13:32 UTC, merged